fix: pre-push hook should run pre-commit hooks on changed, not all files

diff --git a/scripts/setup b/scripts/setup
--- a/scripts/setup
+++ b/scripts/setup
@@ -7,6 +7,14 @@ LANG=C
 . "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/lib.sh"
 
 function setup() {
+    # Install pre-commit for commit-msg hook
+    if pre-commit install -t commit-msg; then
+        out "pre-commit hook is installed."
+    else
+        err "pre-commit hook installation failed"
+        exit "$status_err"
+    fi
+
     REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && git rev-parse --show-toplevel)"
 
     pushd "$REPO_DIR"
@@ -17,22 +25,10 @@ function setup() {
             out "pre-commit hook has been installed." "$symbol_inst"
         else
             err "pre-commit hook installation failed, cannot create symbolic link."
-            exit 1
+            exit "$status_err"
         fi
     else
         out "pre-commit hook is installed."
-    fi
-
-    # Install commit-msg hook if it's not present or doesn't point to the right location
-    if [[ ! -L ".git/hooks/commit-msg" ]] || [ "$(readlink .git/hooks/commit-msg)" != "../../scripts/commit-msg" ]; then
-        if ln -s ../../scripts/commit-msg .git/hooks/commit-msg; then
-            out "commit-msg hook has been installed." "$symbol_inst"
-        else
-            err "commit-msg hook installation failed, cannot create symbolic link."
-            exit 1
-        fi
-    else
-        out "commit-msg hook is installed."
     fi
 
     # Install pre-push hook if it's not present or doesn't point to the right location
@@ -41,7 +37,7 @@ function setup() {
             out "pre-push hook has been installed." "$symbol_inst"
         else
             err "pre-push hook installation failed, cannot create symbolic link."
-            exit 1
+            exit "$status_err"
         fi
     else
         out "pre-push hook is installed."
