feat: add git-merge-commit hook

diff --git a/scripts/setup b/scripts/setup
--- a/scripts/setup
+++ b/scripts/setup
@@ -31,6 +31,18 @@ function setup() {
         out "pre-commit hook is installed."
     fi
 
+    # Install pre-merge-commit hook if it's not present or doesn't point to the right location
+    if [[ ! -L ".git/hooks/pre-merge-commit" ]] || [ "$(readlink .git/hooks/pre-merge-commit)" != "../../scripts/pre-commit" ]; then
+        if ln -s ../../scripts/pre-commit .git/hooks/pre-merge-commit; then
+            out "pre-merge-commit hook has been installed." "$symbol_inst"
+        else
+            err "pre-merge-commit hook installation failed, cannot create symbolic link."
+            exit "$status_err"
+        fi
+    else
+        out "pre-merge-commit hook is installed."
+    fi
+
     # Install pre-push hook if it's not present or doesn't point to the right location
     if [[ ! -L ".git/hooks/pre-push" ]] || [ "$(readlink .git/hooks/pre-push)" != "../../scripts/pre-push" ]; then
         if ln -s ../../scripts/pre-push .git/hooks/pre-push; then
